name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --no-cache -t my-react-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-react-app my-dockerhub-username/my-react-app:latest
          docker push my-dockerhub-username/my-react-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check if container is running
        run: |
          if [ "$(docker ps -q -f name=my-react-container)" ]; then
            echo "Container is running."
          else
            echo "Container is not running."
          fi

      - name: Stop and remove old container
        run: |
          docker stop my-react-container || true
          docker rm my-react-container || true

      - name: Run new Docker container
        run: |
          docker run -d --name my-react-container -p 3001:3001 my-react-app

      - name: Verify container logs
        run: |
          docker logs my-react-container

      - name: Check if the application is accessible
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:3001 | grep 200 || exit 1

