name: Deploy React App

on:
  push:
    branches:
      - main # or the branch you want to trigger the pipeline

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build Docker image
        run: docker build -t my-react-app .

      - name: Save Docker image as artifact
        run: docker save my-react-app -o docker-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: docker-image.tar

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} '
            # Ensure Docker is running
            sudo systemctl start docker || true
            # Load Docker image
            docker load -i docker-image.tar
            # Stop and remove existing container
            docker stop my-react-container || true
            docker rm my-react-container || true
            # Run new Docker container
            docker run -d --name my-react-container -p 80:80 my-react-app
          '
